spring:
  application:
    name: h5-api

  redis:

    # Redis服务器地址
    host: 127.0.0.1

    # Redis服务器连接端口
    port: 6379

    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8

        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

        # 连接池中的最大空闲连接
        max-idle: 8

        # 连接池中的最小空闲连接
        min-idle: 0

server:
  port: 8099

dubbo:
  consumer:

    #关闭所有服务的启动时检查
    check: false

    cluster: failfast

  provider:
    cluster: failfast


  registry:
    address: zookeeper://192.168.3.99:2181
    group: qa


#设置秒杀队列长度
seckillGoods:
  queueSize: 100000