
server.port: 8093

#扫描mapper.xml 包
mybatis:
  mapper-locations: /mapper/*.xml


#数据配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qa_questionnare_sys
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  application:
    name: qa-marketing
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: presentIntegral

#dubbo配置
dubbo:
  registry:
    address: zookeeper://192.168.3.99:2181
    group: qa

  protocol:
    name: dubbo
    port: 8897

  #扫描的包
  scan:
    base-packages: com.ps.service.impl


#线程池的调度的容量配置
threadPool:
  corePoolSize: 3
  maximumPoolSize: 20
